back_office:
    resource: "@BackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /admin

font_office:
    resource: "@FontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /fo

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
